Repository GopeedLab/browser-extension, pull requests merged in 2025-02, with the labels that each got.

#52 docs: add tutorials
  README.md
  README_zh-CN.md
  _docs/img/guide/server-config-step-1.jpg
  _docs/img/guide/server-config-step-2.jpg
  _docs/img/guide/server-config-step-3.jpg
  _docs/img/guide/server-config.jpg
  _docs/img/store/chrome-web-store.png
  _docs/img/store/chrome-web-store.svg
  _docs/img/store/firefox-add-ons.png
  _docs/img/store/firefox-add-ons.svg
  _docs/img/store/microsoft-store.png
  _docs/img/store/microsoft-store.svg
  _docs/img/tutorial/en_api.png
  _docs/img/tutorial/en_settings.png
  _docs/img/tutorial/en_temp_disabled.png
  _docs/img/tutorial/zhcn_api.png
  _docs/img/tutorial/zhcn_settings.png
  _docs/img/tutorial/zhcn_temp_disabled.png
Labels: documentation

#53 fix: fallback when native port connect fail
  background/index.ts
Labels: bug

#55 fix: firefox download filesize handle
  background/index.ts
  options/components/BasicSettings.tsx
  options/components/SavedTip.tsx
Labels: bug

#57 fix: min file size filter on firefox
  background/index.ts
  package.json
Labels: bug

#58 feat: support disable capture when hold ctrl key
  background/index.ts
  background/messages/api/skip.ts
  background/ports/notify.ts
  contents/skip.tsx
  locales/en/messages.json
  locales/zh/messages.json
  options/components/BasicSettings.tsx
  options/types.ts
  types.ts
  util.ts
Labels: enhancement

#61 docs: fix firefox extension page link
  README.md
  README_zh-CN.md
Labels: documentation
